# Generated by Django 4.1.1 on 2022-12-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                (
                    "email",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that email address already exists."
                        },
                        max_length=256,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
            ],
        ),
    ]
